#!/bin/sh
# Audio Control
steps="${2:-5}"

# "pulsemixer" is required
case "$1" in
  toggle) pulsemixer --toggle-mute ;;
  up) pulsemixer --change-volume +"$steps" ;;
  down) pulsemixer --change-volume -"$steps" ;;
  *) exit 1 ;;
esac 2>/dev/null
refstatus 2>/dev/null
# sysnotify 2>/dev/null
# xobcontrol show volume
