#!/bin/sh

(xrandr | grep -v " connected primary" | grep " connected") > /dev/null || exit
resolution=$(xrandr | sed -ne '/^HDMI-A-0/ { :a; n; p; ba;  }' | awk '{print $1}' | dmenu -l 10 -p "HDMI Resolution")

[ -z "$resolution" ] && exit 1
position=$(echo "same-as\nabove\nbelow\nright-of\nleft-of" | dmenu -l 5 -p "Position")

xrandr --output HDMI-A-0 --$position eDP --mode "$resolution"
