#!/bin/sh

primary=$(xrandr | grep " connected primary" | awk '{print $1}')
[ -z "$primary" ] && exit 1
port=$(xrandr | grep -v " connected primary" | grep " connected" | awk '{print $1}END{print "Disconnect"}' | dmenu -i -l 20 -p "Connected Port")
[ -z "$port" ] && exit 1

if [ "$port" = 'Disconnect' ]; then
  dport=$(xrandr | grep -v " connected primary" | grep " connected" | awk '{print $1}' | dmenu -i -l 20 -p "Disconnect Port")
  xrandr --output $primary --auto --output $dport --off
else
  position=$(echo "same-as\nabove\nbelow\nright-of\nleft-of" | dmenu -l 5 -p "Position $primary (Primary)")
  [ -z "$position" ] && exit 1
  xrandr --output $port --auto --$position $primary
fi

setbg restore
