#!/bin/sh
# Toggle dunst
# - libnotify
# - dunst

status="/tmp/.dunsttoggle"
[ -f $status ] &&
(notify-send DUNST_COMMAND_RESUME && rm $status) ||
(notify-send DUNST_COMMAND_PAUSE && echo 1 > $status)
refstatus
