#!/bin/sh

div='|'

printNotification() {
  [ -f /tmp/.dunsttoggle ] && echo 🔕 || echo 🔔
}

printStorage() {
  df -h ~ | grep -v 'Filesystem' | awk '{ print " " $4 }'
}

printDate() {
  date '+🗓 %a %d-%b %H:%M:%S'
}

printAudio() {
  soundnum=$(echo $(amixer sget Master | grep 'Left:' | awk -F"[][]" '{ print $2 }') | sed 's/%//')
  amixer sget Master | grep off >/dev/null &&
    echo 🔇 ||
    ( ([ $soundnum -gt 80 ] && echo 🔊) ||
      ([ $soundnum -gt 20 ] && echo 🔉) ||
      echo 🔈 )
}

printMusic() {
  pgrep mocp >/dev/null && [ ! "$(mocp -Q %file 2>/dev/null)" = ""  ] &&
    ((mocp -i | grep PLAY >/dev/null) && echo "" || echo "") &&
    mocp -Q %song
}

statusBar() {
  printMusic
  [ -z $(wkon anchor)  ] || echo "📁 $(wkon anchor | rev | cut -d'/' -f1 | rev)"
  printStorage
  echo ' 90%'
  printDate
  printAudio
  printNotification
  echo 
}

# Reset while enter xorg
[ -f /tmp/.dunsttoggle ] && rm /tmp/.dunsttoggle

while :; do
  xsetroot -name " $( statusBar | tr '\n' ' ')" #Change newline to space
  sleep 10
done
