#!/bin/sh

div='|'

printNotification() {
  [ -f /tmp/.dunsttoggle ] && echo 🔕 || echo 🔔
}

printStorage() {
  df -h ~ | grep -v 'Filesystem' | awk '{ print " " $4 }'
}

printDate() {
  date '+🗓 %a %d-%b %H:%M:%S'
}

printAudio() {
  sound=$(amixer sget Master | grep 'Left:' | awk -F"[][]" '{ print $2 }')
  soundnum=$(echo $sound | sed 's/%//')
  amixer sget Master | grep off >/dev/null &&
    echo 🔇 ||
    ( ([ $soundnum -gt 66 ] && echo 🔊) ||
      ([ $soundnum -gt 33 ] && echo 🔉) ||
      echo 🔈 )
  echo $sound
}

statusBar() {
  printStorage
  echo ' 90%'
  echo '🌞 50%'
  printAudio
  printDate
  printNotification
  echo 直
}

while :; do
  xsetroot -name " $( statusBar | tr '\n' ' ')" #Change newline to space
  sleep 30
done
