#!/bin/sh
# dmenu shortcut for Logout/Reboot/Shutdown
# - dmenu
#   Show option

case "$(echo "Logout\nReboot\nSuspend\nHibernate\nShutdown\nReload" | dmenu -i -p 'Power Options')" in
  Logout) pkill Xorg ;;
  Reboot) sudo systemctl reboot ;;
  Suspend) sudo systemctl suspend-then-hibernate ;;
  Hibernate) sudo systemctl hibernate ;;
  Shutdown) sudo shutdown -h now ;;
  Reload) xdotool key super+shift+F12 ;;
  *) ;;
esac
