#!/bin/sh
# Kill the status bar sleep in while loop to refresh
# kill $(pstree -lp | grep -- dwm_status\([0-9] | awk -F"sleep" '{gsub(/[()]/,""); print $2;}')
delay="${1:-0}"
sleep $delay &&
/bin/pgrep dwm_status_loop > /dev/null &&
/bin/pkill dwm_status_loop
