#!/bin/sh
# Take a screen and put it in clipboard
# Required:
#   - scrot
#   - xclip
#   - libnotify
#   - dunst

screenshot="/tmp/screenshot$(date '+%Y%m%d%H%M%S').png"

fullscreen() {
  (scrot --silent --overwrite --pointer $screenshot &&
    xclip -f -selection clipboard -t image/png -i $screenshot &&
    notify-send --icon="$screenshot" "Screenshot" "In clipboard & /tmp") ||
  notify-send "Screenshot Fail"
}

selection() {
  flameshot gui
}

case "$1" in
  f|full) fullscreen ;;
  s|select) selection ;;
esac
