#!/bin/sh
# Take a screen and put it in clipboard
# Required:
#   - scrot
#   - xclip
#   - libnotify
#   - dunst

screenshot="/tmp/screenshot.png"

fullscreen() {
  (scrot -op $screenshot &&
    xclip -f -selection clipboard -t image/png -i $screenshot &&
    notify-send --icon="$screenshot" "Screenshot" "In clipboard & /tmp") ||
  notify-send "Screenshot Fail"
}

selection() {
  (scrot --overwrite --pointer  --freeze --select $screenshot &&
    xclip -f -selection clipboard -t image/png -i $screenshot &&
    notify-send --icon="$screenshot" "Screenshot" "In clipboard & /tmp") ||
  notify-send "Screenshot Fail"
}

case "$1" in
  full) fullscreen ;;
  select) sleep 0.2 && selection ;;
esac
