#!/bin/sh


showVolume() {
  volume=$(pulsemixer --get-volume | cut -d' ' -f1)
  [ $(pulsemixer --get-mute) -eq 1 ] && mute='!'
  volumeIcon='🔊'
  if [ "$mute" = '!' ]; then
    volumeIcon='🔇'
  else
    volumeIcon='🔊'
  fi
  dunstify -r 8082 -h int:value:$volume "$volumeIcon Volume"
}

showBrightness() {
  brightness=$(xbacklight -get)
  dunstify -r 8081 -h int:value:$brightness "🌞 Brightness"
}

case "$1" in
  volume) showVolume ;;
  brightness) showBrightness ;;
  *) echo "Invalid argument" ;;
esac
