#!/bin/sh
# Change directory when starting shell
# Put it in .bashrc:
# [ -z $(wkon anchor) ] || cd $(wkon anchor)
wkon_tmp="/tmp/.wkon"
last="$HOME/.config/.last_wkon"
case "$1" in
  h|home)
    rm $wkon_tmp 2>/dev/null && refstatus && exit 0 ;;
  l|last)
    cat $last ;;
  a|anchor)
    [ -f $wkon_tmp ] && cat $wkon_tmp || echo ;;
  "")
    wkon="$(pwd)" && echo "$wkon" > $wkon_tmp && echo $wkon > "$last" && refstatus ;;
esac
