swipe:
  3:
    left:
      command: 'xdotool key alt+shift+Tab' # Next active tag
    right:
      command: 'xdotool key alt+Tab' # Previous active tag
    up:
      command: 'xdotool key super+f' # Toggle full screen
    down:
      command: 'xdotool key super+f' # Toggle full screen
  4:
    left:
      command: 'xdotool key super+k' # Previous window
    right:
      command: 'xdotool key super+j' # Next window
    up:
      command: 'xdotool key super+q' # Close window
      threshold: 0.5
      interval: 1
    down:
      command: 'xdotool key super+1' # First tag

pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus' # Zoom in
    out:
      command: 'xdotool key ctrl+minus' # Zoom out

rotate:
  3:
    clockwise:
      command: 'xdotool key XF86AudioRaiseVolume' # Raise Volume
    counterclockwise:
      command: 'xdotool key XF86AudioLowerVolume' # Lower Volume
  4:
    clockwise:
      command: 'xdotool key XF86MonBrightnessUp' # Increase Brightness
    counterclockwise:
      command: 'xdotool key XF86MonBrightnessDown' # Decrease Brightness

threshold:
  swipe: 0.2
  pinch: 0.5
  rotate: 0.3
