#!/bin/sh

bat=$(cat /sys/class/power_supply/BAT0/capacity)
bat_status=$(cat /sys/class/power_supply/BAT0/status)
[ "$bat_status" = "Charging" ] && echo  ||
  ( ([ $bat -gt 90 ] && echo ) ||
    ([ $bat -gt 80 ] && echo ) ||
    ([ $bat -gt 70 ] && echo ) ||
    ([ $bat -gt 60 ] && echo ) ||
    ([ $bat -gt 50 ] && echo ) ||
    ([ $bat -gt 40 ] && echo ) ||
    ([ $bat -gt 30 ] && echo ) ||
    ([ $bat -gt 20 ] && echo ) ||
    ([ $bat -gt 10 ] && echo ) ||
    echo  )
echo "$bat%"
